name: Deploy to Azure

on:
  push:
    branches:
      - main

env:
    REGISTRY: ${{ secrets.AZURE_REGISTRY }}
    IMAGE_BACKEND: ${{ secrets.AZURE_REGISTRY }}/yp_backend
    IMAGE_FRONTEND: ${{ secrets.AZURE_REGISTRY }}/yp_frontend

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Log in to Azure Container Registry
          uses: docker/login-action@v2
          with:
            registry: ${{ secrets.AZURE_REGISTRY }}
            username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
            password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

        - name: Build and push backend
          run: |
            docker build -t $IMAGE_BACKEND ./server
            docker push $IMAGE_BACKEND

        - name: Build and push frontend
          run: |
            docker build -t $IMAGE_FRONTEND ./client
            docker push $IMAGE_FRONTEND