name: Trigger auto deployment for yp-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/yp-backend-AutoDeployTrigger-dcfdfb18-93ad-49cf-b91c-2dfd275108f6.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.YPBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.YPBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.YPBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: yinkaregistry.azurecr.io
          registryUsername: ${{ secrets.YPBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.YPBACKEND_REGISTRY_PASSWORD }}
          containerAppName: yp-backend
          resourceGroup: portfolio-rg
          imageToBuild: yinkaregistry.azurecr.io/yp-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


